name: main

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  screenshots:
    uses: ./.github/workflows/ci.yaml
    with:
      repository: canonical/ubuntu-desktop-installer
      branch: main
      working-directory: packages/ubuntu_desktop_installer
      flutter-version: '3.10.x'
