name: main

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  bootstrap:
    uses: ./.github/workflows/ci.yaml
    with:
      repository: canonical/ubuntu-desktop-provision
      branch: main
      working-directory: packages/ubuntu_bootstrap
      output-directory: bootstrap

  init:
    uses: ./.github/workflows/ci.yaml
    with:
      repository: canonical/ubuntu-desktop-provision
      branch: main
      working-directory: packages/ubuntu_init
      output-directory: init
