name: main

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  bootstrap:
    uses: ./.github/workflows/ci.yaml
    with:
      repository: canonical/ubuntu-desktop-provision
      branch: main
      working-directory: packages/ubuntu_bootstrap
      output-directory: bootstrap
      flutter-version: '3.10.x'

  init:
    uses: ./.github/workflows/ci.yaml
    with:
      repository: canonical/ubuntu-desktop-provision
      branch: main
      working-directory: packages/ubuntu_init
      output-directory: init
      flutter-version: '3.10.x'
